version: 2
references:
  default_container_config: &default_container_config
    docker:
      - image: cimg/node:14.18

  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/project

  only_version_tags: &only_version_tags
    tags:
      only: /^v.*$/

jobs:
  install:
    <<: *default_container_config
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Run tests
          command: npm test

  release_npm:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Setup npm credentials
          command: echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Publish npm package
          command: ./node_modules/.bin/npm-prepublish --verbose && npm publish --access public

  release_ghpr:
    <<: *default_container_config
    steps:
      - *attach_workspace
      - run:
          name: Setup npm credentials
          command: printf "registry=https://npm.pkg.github.com/\n//npm.pkg.github.com/:_authToken=${GHPR_AUTH_TOKEN}" > ${HOME}/.npmrc
      - run:
          name: Publish npm package
          command: ./node_modules/.bin/npm-prepublish --verbose && npm publish

workflows:
  version: 2
  build-and-release:
    jobs:
      - install:
          filters:
            <<: *only_version_tags
      - test:
          requires:
            - install
          filters:
            <<: *only_version_tags
      - release_npm:
          requires:
            - install
            - test
          filters:
            <<: *only_version_tags
            branches:
              ignore: /.*/
      - release_ghpr:
          requires:
            - install
            - test
          filters:
            <<: *only_version_tags
            branches:
              ignore: /.*/
