version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: node:7
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run:
          name: ESLint
          command: ./node_modules/.bin/eslint -- .
      - run:
          name: Compile with babel
          command: npm run build
      # TEMPORARILY DISABLED
      # - run:
      #     name: AVA tests
      #     command: ./node_modules/.bin/ava
      - store_artifacts:
          path: dist/
      - deploy:
          name: Maybe publish to npm
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo -e "$NPM_USERNAME\n$NPM_PASSWORD\n$NPM_EMAIL" | npm login
              ./node_modules/.bin/publish
            fi
